# Generated by Django 5.2.3 on 2025-07-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lockcommand',
            name='confirm_password',
        ),
        migrations.AddField(
            model_name='lockcommand',
            name='closetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lockcommand',
            name='opentime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lockcommand',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lockcommand',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lockcommand',
            name='port',
            field=models.CharField(max_length=5),
        ),
    ]
