# Generated by Django 5.2.3 on 2025-07-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0002_remove_lockcommand_confirm_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockcommand',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
