# Generated by Django 5.2.3 on 2025-07-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0003_lockcommand_confirm_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lockcommand',
            name='closetime',
        ),
        migrations.RemoveField(
            model_name='lockcommand',
            name='opentime',
        ),
        migrations.RemoveField(
            model_name='lockcommand',
            name='used',
        ),
        migrations.AlterField(
            model_name='lockcommand',
            name='confirm_password',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
    ]
