# Generated by Django 5.2.3 on 2025-07-02 11:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0004_remove_lockcommand_closetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lockcommand',
            old_name='confirmed',
            new_name='is_opened',
        ),
        migrations.RemoveField(
            model_name='lockcommand',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='lockcommand',
            name='created_at',
        ),
        migrations.AddField(
            model_name='lockcommand',
            name='intime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lockcommand',
            name='outtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lockcommand',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lockcommand',
            name='port',
            field=models.IntegerField(),
        ),
    ]
