# Generated by Django 5.2.3 on 2025-07-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0005_rename_confirmed_lockcommand_is_opened_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockcommand',
            name='opentime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
