# Generated by Django 5.2.3 on 2025-07-03 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0006_lockcommand_opentime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lockcommand',
            name='is_opened',
        ),
    ]
