# Generated by Django 5.2.3 on 2025-07-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0007_remove_lockcommand_is_opened'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockcommand',
            name='out_opened',
            field=models.BooleanField(default=False),
        ),
    ]
